import type { IconType } from 'react-icons';
import {
  LuActivity,
  LuAlarmClock,
  LuAnchor,
  LuArrowLeft,
  LuAward,
  LuBanknote,
  LuBell,
  LuBike,
  LuBug,
  LuBuilding2,
  LuCake,
  LuCar,
  LuCat,
  LuCloud,
  LuCompass,
  LuCpu,
  LuCreditCard,
  LuCrown,
  LuDatabase,
  LuDog,
  LuDumbbell,
  LuFilm,
  LuFlag,
  LuFlame,
  LuGamepad2,
  LuGift,
  LuGraduationCap,
  LuGuitar,
  LuHammer,
  LuHouse,
  LuKey,
  LuLaptop,
  LuLibrary,
  LuMail,
  LuMap,
  LuMessageCircle,
  LuMic,
  LuMountain,
  LuNewspaper,
  LuNotebook,
  LuPackage,
  LuPaintbrush,
  LuPhone,
  LuPiggyBank,
  LuPill,
  LuPizza,
  LuPlane,
  LuPuzzle,
  LuRocket,
  LuScissors,
  LuServer,
  LuShield,
  LuShoppingBag,
  LuShoppingCart,
  LuSmile,
  LuStethoscope,
  LuSunrise,
  LuTarget,
  LuTicket,
  LuTrees,
  LuTrophy,
  LuTruck,
  LuTv,
  LuUmbrella,
  LuUsers,
  LuUtensils,
  LuVideo,
  LuWallet,
  LuWaves,
  LuWrench,
  LuArrowUpRight,
  LuBookOpen,
  LuBold,
  LuBookmark,
  LuBox,
  LuBriefcase,
  LuCalendarDays,
  LuCamera,
  LuCheck,
  LuChevronDown,
  LuChevronLeft,
  LuChevronRight,
  LuCircleCheck,
  LuClock,
  LuCode,
  LuCodesandbox,
  LuCoffee,
  LuColumns2,
  LuFileText,
  LuFolder,
  LuEraser,
  LuGlobe,
  LuHash,
  LuHeading1,
  LuHeading2,
  LuHeading3,
  LuHeart,
  LuItalic,
  LuLayoutGrid,
  LuLeaf,
  LuLightbulb,
  LuLink,
  LuList,
  LuListOrdered,
  LuListTodo,
  LuMapPin,
  LuMinus,
  LuMoon,
  LuMusic,
  LuPalette,
  LuPanelLeftClose,
  LuPanelLeftOpen,
  LuPencil,
  LuPlus,
  LuQuote,
  LuRows2,
  LuSearch,
  LuSettings,
  LuSprout,
  LuStar,
  LuStrikethrough,
  LuSun,
  LuTag,
  LuTrash2,
  LuUnderline,
  LuUser,
  LuWaypoints,
  LuX,
  LuZap,
} from 'react-icons/lu';

const UI: Record<string, IconType> = {
  grid: LuLayoutGrid,
  calendar: LuCalendarDays,
  graph: LuWaypoints,
  search: LuSearch,
  plus: LuPlus,
  'chevron-left': LuChevronLeft,
  'chevron-right': LuChevronRight,
  'chevron-down': LuChevronDown,
  pencil: LuPencil,
  'arrow-left': LuArrowLeft,
  'arrow-up-right': LuArrowUpRight,
  sun: LuSun,
  moon: LuMoon,
  star: LuStar,
  'star-filled': LuStar,
  trash: LuTrash2,
  check: LuCheck,
  x: LuX,
  link: LuLink,
  sprout: LuSprout,
  doc: LuFileText,
  settings: LuSettings,
  clock: LuClock,
  zap: LuZap,
  hash: LuHash,
  h1: LuHeading1,
  h2: LuHeading2,
  h3: LuHeading3,
  list: LuList,
  'list-ordered': LuListOrdered,
  'list-todo': LuListTodo,
  quote: LuQuote,
  minus: LuMinus,
  bold: LuBold,
  italic: LuItalic,
  underline: LuUnderline,
  strike: LuStrikethrough,
  palette: LuPalette,
  eraser: LuEraser,
  code: LuCode,
  'code-block': LuCodesandbox,
  columns: LuColumns2,
  rows: LuRows2,
  'panel-close': LuPanelLeftClose,
  'panel-open': LuPanelLeftOpen,
  smile: LuSmile,
  'circle-check': LuCircleCheck,
  'message-circle': LuMessageCircle,
  people: LuUsers,
  cake: LuCake,
  gift: LuGift,
  mail: LuMail,
  phone: LuPhone,
  user: LuUser,
  briefcase: LuBriefcase,
  'map-pin': LuMapPin,
  globe: LuGlobe,
  layout: LuLayoutGrid,
  rows3: LuRows2,
};

export function Icon({ name, size = 16, className }: { name: string; size?: number; className?: string }) {
  const C = UI[name];
  if (!C) return null;
  return <C size={size} className={className} style={name === 'star-filled' ? { fill: 'currentColor' } : undefined} />;
}

/** Curated icon vocabulary for object types. Keys are stored in the DB. */
export const TYPE_ICONS: Record<string, IconType> = {
  'file-text': LuFileText,
  'circle-check': LuCircleCheck,
  folder: LuFolder,
  user: LuUser,
  'calendar-days': LuCalendarDays,
  box: LuBox,
  book: LuBookOpen,
  bulb: LuLightbulb,
  heart: LuHeart,
  bookmark: LuBookmark,
  tag: LuTag,
  globe: LuGlobe,
  briefcase: LuBriefcase,
  coffee: LuCoffee,
  code: LuCode,
  music: LuMusic,
  camera: LuCamera,
  leaf: LuLeaf,
  pin: LuMapPin,
  sprout: LuSprout,
  zap: LuZap,
  home: LuHouse,
  users: LuUsers,
  building: LuBuilding2,
  mail: LuMail,
  phone: LuPhone,
  'message-circle': LuMessageCircle,
  bell: LuBell,
  key: LuKey,
  shield: LuShield,
  target: LuTarget,
  trophy: LuTrophy,
  award: LuAward,
  crown: LuCrown,
  flag: LuFlag,
  flame: LuFlame,
  rocket: LuRocket,
  activity: LuActivity,
  dumbbell: LuDumbbell,
  bike: LuBike,
  mountain: LuMountain,
  waves: LuWaves,
  trees: LuTrees,
  sunrise: LuSunrise,
  cloud: LuCloud,
  compass: LuCompass,
  map: LuMap,
  plane: LuPlane,
  car: LuCar,
  truck: LuTruck,
  anchor: LuAnchor,
  wallet: LuWallet,
  banknote: LuBanknote,
  'credit-card': LuCreditCard,
  'piggy-bank': LuPiggyBank,
  'shopping-cart': LuShoppingCart,
  'shopping-bag': LuShoppingBag,
  gift: LuGift,
  package: LuPackage,
  ticket: LuTicket,
  'graduation-cap': LuGraduationCap,
  library: LuLibrary,
  newspaper: LuNewspaper,
  notebook: LuNotebook,
  laptop: LuLaptop,
  cpu: LuCpu,
  server: LuServer,
  database: LuDatabase,
  bug: LuBug,
  wrench: LuWrench,
  hammer: LuHammer,
  paintbrush: LuPaintbrush,
  scissors: LuScissors,
  puzzle: LuPuzzle,
  'gamepad-2': LuGamepad2,
  film: LuFilm,
  tv: LuTv,
  video: LuVideo,
  mic: LuMic,
  guitar: LuGuitar,
  utensils: LuUtensils,
  pizza: LuPizza,
  cake: LuCake,
  'alarm-clock': LuAlarmClock,
  stethoscope: LuStethoscope,
  pill: LuPill,
  smile: LuSmile,
  cat: LuCat,
  dog: LuDog,
  umbrella: LuUmbrella,
};

export const ICON_CHOICES = Object.keys(TYPE_ICONS);

export function TypeIcon({ icon, color, size = 16 }: { icon?: string; color?: string; size?: number }) {
  const C = icon ? TYPE_ICONS[icon] : undefined;
  if (C) return <C size={size} style={color ? { color } : undefined} />;
  // Legacy fallback: user-created types from the emoji era render their emoji as-is.
  if (icon) return <span style={{ fontSize: size - 1, lineHeight: 1 }}>{icon}</span>;
  return <LuBox size={size} style={color ? { color } : undefined} />;
}
